# Default values for demochart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
environment: dev
appname: nodejs
image:
  repository: aganeshkumar1222/hackathon-nodejs
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
service:
  type: LoadBalancer
  port: 80
