apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appname }}"
  namespace: "{{ .Values.namespace }}"
  labels:
     app : "{{ .Values.appname }}"
     environment: "{{ .Values.environment }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app : "{{ .Values.appname }}"
  template:
    metadata:
      labels:
        app : "{{ .Values.appname }}"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
          - name: MONGODB_URI
            valueFrom:
             secretKeyRef:
               name: mongosecret
               key: mongourl
          ports:
          - containerPort: 8080
