apiVersion: v1
kind: Service
metadata:
  name: "{{ .values.servicename }}"
  labels:
    app : "{{ .Values.appname }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app : "{{ .Values.appname }}"
